import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Utilities/Navbar";
import Footer from "./components/Utilities/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});
export const metadata = {
  title: "Recomtel",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${poppins.className}`}>
      <body>

        {children}

      </body>
    </html>
  );
}
